### ISSUE TITLE
Commands 

### ISSUE THREAD

**Issue by feudall** [charlie-x/eakins-camera#1]
Hi, friend.  It is possible in more detail what commands can be written to the terminal.  there is a list of possible commands.  I will be grateful for any help.

**Comment by charlie-x** [comment]
this should help

[https://charliex2.wordpress.com/2020/01/14/eakins-camera-hackery-pokery-and-the-legend-of-measuretwice/](https://charliex2.wordpress.com/2020/01/14/eakins-camera-hackery-pokery-and-the-legend-of-measuretwice/)
