### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 744036292** [charlie-x/eakins-camera#2]
Hello, is it convenient for you to give me your contact information? I have some questions to ask you

**Comment by feudall** [comment]
что именно вас интересует?
тел 9253390042
  
>Четверг, 26 мая 2022, 20:07 +03:00 от 744036292 ***@***.***>:
> 
> 
>Здравствуйте, не могли бы вы дать мне свои контактные данные?  У меня есть несколько вопросов, чтобы задать вам
>— 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отмените подписку . 
>Вы получаете это, потому что подписаны на эту тему. Идентификатор сообщения:  <charlie-x/eakins-camera/issues/2  @  github  .  ком> 
 
 
Джокер Джокер

**Comment by 744036292** [comment]
I would like to ask whether your J2534 simulator can simulate the vehicle module of VW model for analog communication

**Comment by 744036292** [comment]
I would like to ask whether your J2534 simulator can simulate the vehicle module of VW model for analog communication

**Comment by 744036292** [comment]
> что именно вас интересует? 来自 9253390042  
> Четверг, 26 мая 2022, 20:07 +03:00 от 744036292 ***@***.***>: Здравствуйте, не могли бы вы дать мне свои контактные данные? У меня есть несколько вопросов, чтобы задать вам — Ответьте на это письмо напрямую, просмотрите его на GitHub или отскените под. Вы получаете это, потому что подписаны на эту тему。Идентификатор сообщения：<charlie-x/eakins-camera/issues/2 @ github 。ком>
>     Джокер Джокер



> 
Can I program the modules with anti-theft function on line, such as analog instrument engine transmission direction lock

**Comment by feudall** [comment]
> симулятор J2534

I don't quite understand what you're talking about.
I can't help you

**Comment by 744036292** [comment]
> 

The J2534 simulator you released, I said whether it can simulate Volkswagen vehicles

**Comment by charlie-x** [comment]
it doesn't simulate any specific vehicle.
